from sqlmodel import SQLModel, Field
from typing import Optional
from datetime import datetime
from sqlalchemy import Column, DateTime


class TaskBase(SQLModel):
    """
    Base class for Task model containing common fields.
    """
    title: str = Field(min_length=1, max_length=255)
    description: Optional[str] = Field(default=None, max_length=1000)
    completed: bool = Field(default=False)
    user_id: str = Field(index=True)  # Index for performance when querying by user


class Task(TaskBase, table=True):
    """
    Task model representing a user's todo item.

    Attributes:
        id: Unique identifier for each task
        title: The main content/description of the task (required, 1-255 chars)
        description: Detailed information about the task (optional, 0-1000 chars)
        completed: Whether the task is completed (default: False)
        user_id: Links the task to a specific user (required, indexed for performance)
        created_at: Timestamp when the task was created
        updated_at: Timestamp when the task was last modified
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: Optional[datetime] = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = Field(default_factory=datetime.utcnow)


class TaskCreate(TaskBase):
    """
    Schema for creating a new task.

    This excludes the id, created_at, and updated_at fields since they are
    auto-generated by the system.
    """
    pass


class TaskRead(TaskBase):
    """
    Schema for reading a task with its ID and timestamps.
    """
    id: int
    created_at: datetime
    updated_at: datetime


class TaskUpdate(SQLModel):
    """
    Schema for updating a task.

    All fields are optional to allow partial updates.
    """
    title: Optional[str] = Field(default=None, min_length=1, max_length=255)
    description: Optional[str] = Field(default=None, max_length=1000)
    completed: Optional[bool] = None


class TaskCreateRequest(SQLModel):
    """
    Schema for validating the request body for task creation.

    This is used for validation at the API level to ensure that the input
    conforms to the required constraints before creating a Task instance.
    """
    title: str = Field(min_length=1, max_length=255)
    description: Optional[str] = Field(default=None, max_length=1000)
    completed: bool = Field(default=False)


class TaskToggle(SQLModel):
    """
    Schema for toggling task completion status.
    """
    completed: bool