import pytest
from src.models.task import Task, TaskCreate, TaskRead, TaskUpdate


def test_task_creation():
    """
    Test creating a Task instance with valid data.
    """
    task_data = {
        "title": "Test Task",
        "description": "Test Description",
        "completed": False,
        "user_id": "user123"
    }

    task = Task(**task_data)

    assert task.title == "Test Task"
    assert task.description == "Test Description"
    assert task.completed is False
    assert task.user_id == "user123"
    assert task.id is None  # ID is generated by the database


def test_task_create_schema():
    """
    Test TaskCreate schema validation.
    """
    task_create_data = {
        "title": "Test Task",
        "description": "Test Description",
        "completed": False,
        "user_id": "user123"
    }

    task_create = TaskCreate(**task_create_data)

    assert task_create.title == "Test Task"
    assert task_create.description == "Test Description"
    assert task_create.completed is False
    assert task_create.user_id == "user123"


def test_task_read_schema():
    """
    Test TaskRead schema validation.
    """
    from datetime import datetime

    task_read_data = {
        "id": 1,
        "title": "Test Task",
        "description": "Test Description",
        "completed": False,
        "user_id": "user123",
        "created_at": datetime.now(),
        "updated_at": datetime.now()
    }

    task_read = TaskRead(**task_read_data)

    assert task_read.id == 1
    assert task_read.title == "Test Task"
    assert task_read.description == "Test Description"
    assert task_read.completed is False
    assert task_read.user_id == "user123"


def test_task_update_schema_partial():
    """
    Test TaskUpdate schema with partial update data.
    """
    # Test with only title
    task_update = TaskUpdate(title="Updated Title")
    assert task_update.title == "Updated Title"
    assert task_update.description is None
    assert task_update.completed is None


def test_task_required_fields():
    """
    Test that required fields are validated.
    """
    # Task without required title should raise validation error
    with pytest.raises(ValueError):
        Task(
            title="",  # Empty title should fail validation
            user_id="user123"
        )


def test_task_title_length_validation():
    """
    Test that title length validation works.
    """
    # Task with title longer than 255 characters should raise validation error
    long_title = "x" * 256

    with pytest.raises(ValueError):
        Task(
            title=long_title,
            user_id="user123"
        )


def test_task_description_max_length():
    """
    Test that description max length validation works.
    """
    # Task with description longer than 1000 characters should raise validation error
    long_description = "x" * 1001

    with pytest.raises(ValueError):
        Task(
            title="Test Task",
            description=long_description,
            user_id="user123"
        )